import type { ScheduledPost } from './calendar.types';

export const mockScheduledPosts: ScheduledPost[] = [
  {
    id: '1',
    title: '10 трендов веб-дизайна 2026',
    date: new Date(2026, 0, 5),
    time: '10:00',
    type: 'scheduled',
    category: 'Дизайн',
  },
  {
    id: '2',
    title: 'React 19: что нового?',
    date: new Date(2026, 0, 7),
    time: '14:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '3',
    title: 'AI в маркетинге: полное руководство',
    date: new Date(2026, 0, 10),
    time: '09:00',
    type: 'ai-suggestion',
    category: 'Маркетинг',
  },
  {
    id: '4',
    title: 'Оптимизация производительности Next.js',
    date: new Date(2026, 0, 12),
    time: '11:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '5',
    title: 'UX-копирайтинг: лучшие практики',
    date: new Date(2026, 0, 15),
    time: '15:00',
    type: 'scheduled',
    category: 'UX',
  },
  {
    id: '6',
    title: 'Вебинар: Дизайн-системы',
    date: new Date(2026, 0, 18),
    time: '16:00',
    type: 'event',
    category: 'События',
  },
  {
    id: '7',
    title: 'Tailwind CSS 4.0: обзор новых функций',
    date: new Date(2026, 0, 3),
    time: '11:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '8',
    title: 'Психология цвета в UI',
    date: new Date(2026, 0, 8),
    time: '13:00',
    type: 'scheduled',
    category: 'Дизайн',
  },
  {
    id: '9',
    title: 'Микроинтеракции: гайд',
    date: new Date(2026, 0, 14),
    time: '10:00',
    type: 'ai-suggestion',
    category: 'UX',
  },
  {
    id: '10',
    title: 'TypeScript для начинающих',
    date: new Date(2026, 0, 20),
    time: '09:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '11',
    title: 'Адаптивная типографика',
    date: new Date(2026, 0, 22),
    time: '14:00',
    type: 'scheduled',
    category: 'Дизайн',
  },
  {
    id: '12',
    title: 'Доступность веб-приложений',
    date: new Date(2026, 0, 25),
    time: '12:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '13',
    title: 'Конференция Frontend 2026',
    date: new Date(2026, 0, 27),
    time: '10:00',
    type: 'event',
    category: 'События',
  },
  {
    id: '14',
    title: 'Анимация в вебе: лучшие практики',
    date: new Date(2026, 0, 29),
    time: '15:00',
    type: 'scheduled',
    category: 'Дизайн',
  },
  {
    id: '15',
    title: 'SEO-оптимизация в 2026',
    date: new Date(2026, 0, 16),
    time: '11:00',
    type: 'ai-suggestion',
    category: 'Маркетинг',
  },
  {
    id: '16',
    title: 'Figma: продвинутые техники',
    date: new Date(2026, 0, 9),
    time: '16:00',
    type: 'scheduled',
    category: 'Дизайн',
  },
  {
    id: '17',
    title: 'Serverless архитектура',
    date: new Date(2026, 0, 13),
    time: '10:30',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '18',
    title: 'A/B тестирование интерфейсов',
    date: new Date(2026, 0, 21),
    time: '13:00',
    type: 'scheduled',
    category: 'UX',
  },
  // Февраль 2026
  {
    id: '19',
    title: 'CSS Grid: продвинутые техники',
    date: new Date(2026, 1, 2),
    time: '10:00',
    type: 'scheduled',
    category: 'CSS',
  },
  {
    id: '20',
    title: 'Vue 3 Composition API',
    date: new Date(2026, 1, 4),
    time: '14:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '21',
    title: 'Контент-маркетинг для технических блогов',
    date: new Date(2026, 1, 6),
    time: '09:00',
    type: 'ai-suggestion',
    category: 'Маркетинг',
  },
  {
    id: '22',
    title: 'Svelte 5: обзор новинок',
    date: new Date(2026, 1, 9),
    time: '11:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '23',
    title: 'Мастер-класс: адаптивный дизайн',
    date: new Date(2026, 1, 11),
    time: '15:00',
    type: 'event',
    category: 'События',
  },
  {
    id: '24',
    title: 'WebAssembly в production',
    date: new Date(2026, 1, 13),
    time: '16:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '25',
    title: 'Design Tokens: стандартизация',
    date: new Date(2026, 1, 5),
    time: '11:00',
    type: 'scheduled',
    category: 'Дизайн',
  },
  {
    id: '26',
    title: 'Progressive Web Apps 2026',
    date: new Date(2026, 1, 7),
    time: '13:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '27',
    title: 'Тренды в motion-дизайне',
    date: new Date(2026, 1, 10),
    time: '10:00',
    type: 'ai-suggestion',
    category: 'Дизайн',
  },
  {
    id: '28',
    title: 'GraphQL с Apollo Client',
    date: new Date(2026, 1, 15),
    time: '09:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '29',
    title: 'Бренд-дизайн для стартапов',
    date: new Date(2026, 1, 17),
    time: '14:00',
    type: 'scheduled',
    category: 'Дизайн',
  },
  {
    id: '30',
    title: 'Тестирование React-компонентов',
    date: new Date(2026, 1, 19),
    time: '12:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '31',
    title: 'Вебинар: AI-инструменты для дизайнеров',
    date: new Date(2026, 1, 21),
    time: '10:00',
    type: 'event',
    category: 'События',
  },
  {
    id: '32',
    title: 'Производительность веб-приложений',
    date: new Date(2026, 1, 24),
    time: '15:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '33',
    title: 'Стратегии контент-календаря',
    date: new Date(2026, 1, 12),
    time: '11:00',
    type: 'ai-suggestion',
    category: 'Маркетинг',
  },
  {
    id: '34',
    title: 'Framer Motion: анимации',
    date: new Date(2026, 1, 8),
    time: '16:00',
    type: 'scheduled',
    category: 'Разработка',
  },
  {
    id: '35',
    title: 'Micro-frontends на практике',
    date: new Date(2026, 1, 14),
    time: '10:30',
    type: 'scheduled',
    category: 'Архитектура',
  },
  {
    id: '36',
    title: 'UX-исследования: методы',
    date: new Date(2026, 1, 18),
    time: '13:00',
    type: 'scheduled',
    category: 'UX',
  },
  {
    id: '37',
    title: 'Node.js 22: новые возможности',
    date: new Date(2026, 1, 26),
    time: '09:00',
    type: 'scheduled',
    category: 'Разработка',
  },
];

export const WEEKDAYS = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'];
