import type { McpApiKey, McpAuditEntry } from './mcp.types';

export const MOCK_API_KEYS: McpApiKey[] = [
  {
    id: '1',
    name: 'Claude Desktop — Николай',
    keyPrefix: 'pw_mcp_a8f3',
    scope: 'admin',
    isActive: true,
    lastUsedAt: '2026-03-21T10:30:00Z',
    expiresAt: null,
    createdAt: '2026-03-15T12:00:00Z',
  },
  {
    id: '2',
    name: 'Cursor — проект PW',
    keyPrefix: 'pw_mcp_7bc2',
    scope: 'write',
    isActive: true,
    lastUsedAt: '2026-03-20T18:45:00Z',
    expiresAt: '2026-06-15T00:00:00Z',
    createdAt: '2026-03-18T09:00:00Z',
  },
  {
    id: '3',
    name: 'CI/CD Pipeline',
    keyPrefix: 'pw_mcp_e1d4',
    scope: 'read',
    isActive: false,
    lastUsedAt: '2026-03-10T14:20:00Z',
    expiresAt: '2026-04-01T00:00:00Z',
    createdAt: '2026-03-01T08:00:00Z',
  },
];

export const MOCK_AUDIT_LOG: McpAuditEntry[] = [
  {
    id: '1',
    timestamp: '2026-03-21T10:30:15Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'list_articles',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 42,
  },
  {
    id: '2',
    timestamp: '2026-03-21T10:30:22Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'get_article',
    resourceType: 'article',
    resourceId: 'prompt-engineering-guide',
    result: 'success',
    durationMs: 28,
  },
  {
    id: '3',
    timestamp: '2026-03-21T10:31:05Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'update_article',
    resourceType: 'article',
    resourceId: 'prompt-engineering-guide',
    result: 'success',
    durationMs: 135,
  },
  {
    id: '4',
    timestamp: '2026-03-21T10:31:45Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'analyze_article_seo',
    resourceType: 'article',
    resourceId: 'prompt-engineering-guide',
    result: 'success',
    durationMs: 310,
  },
  {
    id: '5',
    timestamp: '2026-03-21T10:32:10Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'list_categories',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 18,
  },
  {
    id: '6',
    timestamp: '2026-03-21T10:33:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'publish_article',
    resourceType: 'article',
    resourceId: 'prompt-engineering-guide',
    result: 'success',
    durationMs: 220,
  },
  {
    id: '7',
    timestamp: '2026-03-20T18:45:30Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'create_article',
    resourceType: 'article',
    resourceId: null,
    result: 'success',
    durationMs: 185,
  },
  {
    id: '8',
    timestamp: '2026-03-20T18:46:10Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'upload_media',
    resourceType: 'media',
    resourceId: null,
    result: 'error',
    durationMs: 2340,
    errorMessage: 'File size exceeds 10MB limit',
  },
  {
    id: '9',
    timestamp: '2026-03-20T18:47:05Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'upload_media',
    resourceType: 'media',
    resourceId: 'hero-image-ai-guide.webp',
    result: 'success',
    durationMs: 1850,
  },
  {
    id: '10',
    timestamp: '2026-03-20T18:48:00Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'update_article',
    resourceType: 'article',
    resourceId: 'ai-automation-workflows',
    result: 'success',
    durationMs: 95,
  },
  {
    id: '11',
    timestamp: '2026-03-20T15:12:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'publish_article',
    resourceType: 'article',
    resourceId: 'ai-automation-guide',
    result: 'success',
    durationMs: 198,
  },
  {
    id: '12',
    timestamp: '2026-03-20T15:10:30Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'get_article',
    resourceType: 'article',
    resourceId: 'ai-automation-guide',
    result: 'success',
    durationMs: 31,
  },
  {
    id: '13',
    timestamp: '2026-03-20T14:55:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'generate_slug',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 12,
  },
  {
    id: '14',
    timestamp: '2026-03-19T16:20:00Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'list_articles',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 38,
  },
  {
    id: '15',
    timestamp: '2026-03-19T16:20:45Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'search_articles',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 67,
  },
  {
    id: '16',
    timestamp: '2026-03-19T09:00:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'list_categories',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 22,
  },
  {
    id: '17',
    timestamp: '2026-03-19T09:01:30Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'analyze_article_seo',
    resourceType: 'article',
    resourceId: 'web-monetization-basics',
    result: 'success',
    durationMs: 285,
  },
  {
    id: '18',
    timestamp: '2026-03-19T09:02:15Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'get_content_brief',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 45,
  },
  {
    id: '19',
    timestamp: '2026-03-18T12:30:00Z',
    keyPrefix: 'pw_mcp_e1d4',
    keyName: 'CI/CD Pipeline',
    tool: 'list_articles',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 35,
  },
  {
    id: '20',
    timestamp: '2026-03-18T12:30:15Z',
    keyPrefix: 'pw_mcp_e1d4',
    keyName: 'CI/CD Pipeline',
    tool: 'get_article_stats',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 52,
  },
  {
    id: '21',
    timestamp: '2026-03-18T11:00:00Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'create_category',
    resourceType: 'category',
    resourceId: null,
    result: 'success',
    durationMs: 78,
  },
  {
    id: '22',
    timestamp: '2026-03-18T11:01:00Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'create_tag',
    resourceType: 'tag',
    resourceId: null,
    result: 'success',
    durationMs: 55,
  },
  {
    id: '23',
    timestamp: '2026-03-17T14:00:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'get_system_health',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 120,
  },
  {
    id: '24',
    timestamp: '2026-03-17T14:01:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'get_audit_log',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 88,
  },
  {
    id: '25',
    timestamp: '2026-03-17T10:15:00Z',
    keyPrefix: 'pw_mcp_e1d4',
    keyName: 'CI/CD Pipeline',
    tool: 'get_site_analytics',
    resourceType: null,
    resourceId: null,
    result: 'error',
    durationMs: 5020,
    errorMessage: 'Yandex.Metrika API timeout',
  },
  {
    id: '26',
    timestamp: '2026-03-16T09:30:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'list_media',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 41,
  },
  {
    id: '27',
    timestamp: '2026-03-16T09:31:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'get_seo_settings',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 33,
  },
  {
    id: '28',
    timestamp: '2026-03-15T17:00:00Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'list_tags',
    resourceType: null,
    resourceId: null,
    result: 'success',
    durationMs: 19,
  },
  {
    id: '29',
    timestamp: '2026-03-15T17:01:00Z',
    keyPrefix: 'pw_mcp_7bc2',
    keyName: 'Cursor — проект PW',
    tool: 'schedule_article',
    resourceType: 'article',
    resourceId: 'remote-work-productivity',
    result: 'success',
    durationMs: 142,
  },
  {
    id: '30',
    timestamp: '2026-03-15T13:00:00Z',
    keyPrefix: 'pw_mcp_a8f3',
    keyName: 'Claude Desktop — Николай',
    tool: 'delete_article',
    resourceType: 'article',
    resourceId: 'test-draft-cleanup',
    result: 'success',
    durationMs: 65,
  },
];
