"""002_add_auth_fields_to_user

Revision ID: 4d74c1bd279b
Revises: 58a6e8c0f6af
Create Date: 2026-02-15 22:09:41.627492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d74c1bd279b'
down_revision: Union[str, Sequence[str], None] = '58a6e8c0f6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=200), nullable=True))
    op.create_unique_constraint('uq_user_oauth', 'users', ['oauth_provider', 'oauth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_oauth', 'users', type_='unique')
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
