"""003_add_user_oauth_links

Revision ID: 54973cba4d7d
Revises: 4d74c1bd279b
Create Date: 2026-02-16 14:49:48.492040

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54973cba4d7d'
down_revision: Union[str, Sequence[str], None] = '4d74c1bd279b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_links',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_id', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'oauth_id', name='uq_oauth_link')
    )
    op.create_index(op.f('ix_user_oauth_links_user_id'), 'user_oauth_links', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Миграция данных: перенос существующих OAuth-привязок из users
    op.execute(
        """
        INSERT INTO user_oauth_links (id, user_id, provider, oauth_id, created_at, updated_at)
        SELECT gen_random_uuid(), id, oauth_provider, oauth_id, created_at, now()
        FROM users
        WHERE oauth_provider IS NOT NULL AND oauth_id IS NOT NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_oauth_links_user_id'), table_name='user_oauth_links')
    op.drop_table('user_oauth_links')
    # ### end Alembic commands ###
